USE PETS_DB
GO

create table PETS(ID BIGINT PRIMARY KEY NOT NULL IDENTITY, NAME_PET VARCHAR(30), 
AGE_PET INT, 
BREED_PET VARCHAR(30), 
NICK_NAME_PET VARCHAR(10), 
DATE_CREATE_PET DATETIME, 
DATE_UPDATE_PET DATETIME,
STATUS_PET BIT)

GO

ALTER TABLE PETS
ADD CONSTRAINT UQ_PETS_NAME_STATUS UNIQUE (NAME_PET, STATUS_PET)

GO

ALTER TABLE PETS DROP CONSTRAINT UQ_PETS_ID_NAME;

------------------------------------------------------------------------------------------------------

create table VACCINES(ID BIGINT PRIMARY KEY NOT NULL IDENTITY, NAME_VACCINE VARCHAR(30), 
DATE_GIVEN_VACCINE DATETIME,
NEXT_DUE_VACCINE DATETIME,
DATE_CREATE_VACCINE DATETIME, 
DATE_UPDATE_VACCINE DATETIME,
ID_PET BIGINT NOT NULL,
STATUS_VACCINE BIT)